### ISSUE TITLE
I got Error: "RuntimeError: Internal: unk is not defined."

### ISSUE THREAD

**Issue by NeiH4207** [facebookresearch/llama#287]
> initializing model parallel with size 1
> initializing ddp with size 1
> initializing pipeline with size 1
Loading
Traceback (most recent call last):
  File "/home/hienvq1/AI/llama/example.py", line 119, in <module>
    fire.Fire(main)
  File "/home/hienvq1/.conda/envs/llama/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/hienvq1/.conda/envs/llama/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/hienvq1/.conda/envs/llama/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/hienvq1/AI/llama/example.py", line 78, in main
    generator = load(
  File "/home/hienvq1/AI/llama/example.py", line 54, in load
    tokenizer = Tokenizer(model_path=tokenizer_path)
  File "/home/hienvq1/AI/llama/llama/tokenizer.py", line 17, in __init__
    self.sp_model = SentencePieceProcessor(model_file=model_path)
  File "/home/hienvq1/.conda/envs/llama/lib/python3.10/site-packages/sentencepiece/__init__.py", line 447, in Init
    self.Load(model_file=model_file, model_proto=model_proto)
  File "/home/hienvq1/.conda/envs/llama/lib/python3.10/site-packages/sentencepiece/__init__.py", line 905, in Load
    return self.LoadFromFile(model_file)
  File "/home/hienvq1/.conda/envs/llama/lib/python3.10/site-packages/sentencepiece/__init__.py", line 310, in LoadFromFile
    return _sentencepiece.SentencePieceProcessor_LoadFromFile(self, arg)
RuntimeError: Internal: unk is not defined.
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 767054) of binary: /home/hienvq1/.conda/envs/llama/bin/python
Traceback (most recent call last):
  File "/home/hienvq1/.conda/envs/llama/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/home/hienvq1/.conda/envs/llama/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/home/hienvq1/.conda/envs/llama/lib/python3.10/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/home/hienvq1/.conda/envs/llama/lib/python3.10/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/home/hienvq1/.conda/envs/llama/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/hienvq1/.conda/envs/llama/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
example.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-04-27_15:25:06
  host      : sdc2-bdi-analytic-gpu1
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 767054)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================

How to fix it?

**Comment by zhao1402072392** [comment]
same here, did you fix it?

**Comment by NeiH4207** [comment]
> same here, did you fix it?

**Comment by shihui2010** [comment]
+1

**Comment by ChongWu-Biostat** [comment]
+1

**Comment by luomingshuang** [comment]
+1

**Comment by devymex** [comment]
+1

**Comment by Uralstech** [comment]
Same here with LLaMA -2 7B-chat.

**Comment by yhygta** [comment]
Same here with LLaMA -2 13B-chat.

**Comment by yhygta** [comment]
I found a problem with the downloaded tokenizer.model and tokenizer_checklist.chk, both of which are 0KB. I downloaded these two files again through the download.sh path and the problem was resolved.

**Comment by devymex** [comment]
I found the problem.

The download link in the email is only valid for one day. When you try to download again the next day, you will get an access denied error and got a bad content of files. Try `vim tokenizer.model` you will see the error.

No matter which model, once you fail to download, the `tokenizer.model` will be damaged.

download here: https://github.com/devymex/notes/blob/master/tokenizer.7z

**Comment by Uralstech** [comment]
> I found the problem.
> 
> The download link in the email is only valid for one day. When you try to download again the next day, you will get an access denied error and got a bad content of files. Try `vim tokenizer.model` you will see the error.
> 
> No matter which model, once you fail to download, the `tokenizer.model` will be damaged.
> 
> download here: https://github.com/devymex/notes/blob/master/tokenizer.7z



> I found a problem with the downloaded tokenizer.model and tokenizer_checklist.chk, both of which are 0KB. I downloaded these two files again through the download.sh path and the problem was resolved.

Thanks a lot! That fixed it. I still can't run it as I ran out of VRAM, but that's a different problem.

**Comment by WangYangfan** [comment]
> I found a problem with the downloaded tokenizer.model and tokenizer_checklist.chk, both of which are 0KB. I downloaded these two files again through the download.sh path and the problem was resolved.

thank! very useful!

**Comment by lmarcon** [comment]
It looks like the solution above solves the issue, thanks everyone. Closing
