### ISSUE TITLE
Checking checksums - Could not parse check file 'checklist.chk' (2)

### ISSUE THREAD

**Issue by Anerco** [facebookresearch/llama#362]

**Comment by Mihir2** [comment]
Same error

**Comment by cloudwolf516** [comment]
For additional context, the error occurs when running the download.sh script.

**Comment by joegibes** [comment]
> Checking checksums
> md5sum: checklist.chk: no properly formatted MD5 checksum lines found

Same problem for me. Ubuntu (on WSL)

**Comment by artvandelay** [comment]
Same issue

**Comment by diwasbhattarai** [comment]
Got same error on Ubuntu

**Comment by derwiki-gs** [comment]
Quick workaround: remove this line from `download.sh`
https://github.com/facebookresearch/llama/blob/cfc3fc8c1968d390eb830e65c63865e980873a06/download.sh#L56

**Comment by david-goodfellow** [comment]
I am seeing this as well despite `md5sum` being installed properly in a conda env per description. Also, looking in the output in terminal, it seems 403 error despite being my first download only for `7B` model 
```
HTTP request sent, awaiting response... 403 Forbidden
2023-07-18 16:10:01 ERROR 403: Forbidden.

Checking checksums
md5sum: checklist.chk: no properly formatted MD5 checksum lines found
```

**Comment by Mihir2** [comment]
Requesting the link again, seems to be working with the new link as described here: https://github.com/facebookresearch/llama/issues/360#issuecomment-1640889338

**Comment by derwiki-gs** [comment]
same as @david-goodfellow I am getting sporadic 403s

**Comment by pblan** [comment]
Also try to exit any VPN you might have turned on.
That solved it for me!

**Comment by david-goodfellow** [comment]
> Quick workaround: remove this line from `download.sh`
> 
> https://github.com/facebookresearch/llama/blob/cfc3fc8c1968d390eb830e65c63865e980873a06/download.sh#L56

somehow I feel this will just lead to hard to debug issues down the line 🤔

**Comment by owquresh** [comment]
> 

requesting did not work for me

**Comment by Levinin** [comment]
Similar, but I get unsupported browser and no valid checksums. Looks like it copies the HTTP response into the place of checklist.chk since it doesn't get the checksum file itself. Commenting the line doesn't work since it still fails due to unsupported browser error, whatever that means in this context. Running Ubuntu.

---
Connecting to l.facebook.com (l.facebook.com)|2a03:2880:f158:84:face:b00c:0:14c9|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://www.facebook.com/unsupportedbrowser [following]
--2023-07-18 21:50:16--  https://www.facebook.com/unsupportedbrowser

**Comment by tbbuck** [comment]
Check that you've copied the URL in the email, and not the href value, i.e. what you get when you right-click on a link and select "Copy Link." 

If the value you've pasted into download.sh begins with https://l.facebook.com instead of https://download.llamameta.net then you've copied it wrong :)

**Comment by mscott5861** [comment]
Not connected to VPN. Re-requested link, but second link didn't work, either.  403s for every request. Tried on Ubuntu 20.04 and Ubuntu on WSL.

**Comment by DamithDR** [comment]
![image](https://github.com/facebookresearch/llama/assets/17285848/f165fd07-e93a-447c-a4ab-3208baea0156)
Same issue. Not working with new link too.

**Comment by aptl26** [comment]
> Check that you've copied the URL in the email, and not the href value, i.e. what you get when you right-click on a link and select "Copy Link."
> 
> If the value you've pasted into download.sh begins with https://l.facebook.com instead of https://download.llamameta.net then you've copied it wrong :)

This solved it for me. Thanks

**Comment by Levinin** [comment]
> Check that you've copied the URL in the email, and not the href value, i.e. what you get when you right-click on a link and select "Copy Link."
> 
> If the value you've pasted into download.sh begins with https://l.facebook.com instead of https://download.llamameta.net then you've copied it wrong :)

Rookie error, thank you!

**Comment by chrismarra** [comment]
Hi everyone, we fixed some issues with the download links yesterday - resetting your local directory and requesting a new link is the best way to start over unless you've already verified checksums and know exactly which files you need. Make sure you're requesting a fresh link, copying the actual text of the link (download.llamameta.net), and starting from a fresh local directory. Sorry for the issues yesterday!

**Comment by DamithDR** [comment]
@chrismarra For some reason I still get the same issue after re-cloning and trying with a new link. (full fresh start)

**Comment by mscott5861** [comment]
@chrismarra I too still have the 403 issue, despite a fresh local directory and a fresh+correct download hyperlink. Tried on two systems (Ubuntu 20.04 on both). 

Starlink is my ISP, if by any chance CGNAT could be causing these issues.

**Comment by digiguru** [comment]
It's worth mentioning you need to read the question it asks.

It says 
```
Enter the URL from email: 
```

If you are on auto-pilot you might read it as 

```
Enter blah blah email:
```

You need to paste in the URL that starts 

```
https://download.llamameta.net/...)
```

Hope that helps people struggling

**Comment by m5a0r7** [comment]
Try to define PRESIGNED_URL and MODEL_SIZE in ./download.sh as:

PRESIGNED_URL="Your URL"
MODEL_SIZE="The Model Size You Want"

instead of read -p "Enter the URL from email: " PRESIGNED_URL

**Comment by ShaunMoore** [comment]
> It's worth mentioning you need to read the question it asks.
> 
> It says
> 
> ```
> Enter the URL from email: 
> ```
> 
> If you are on auto-pilot you might read it as
> 
> ```
> Enter blah blah email:
> ```
> 
> You need to paste in the URL that starts
> 
> ```
> https://download.llamameta.net/...)
> ```
> 
> Hope that helps people struggling

This was actually helpful as I was on said "autopilot" lol. Entered the URL instead of continually being an idiot and entering my email.

Don't understand why people are getting upset. Thanks man.

**Comment by steveoOn** [comment]
> > It's worth mentioning you need to read the question it asks.
> > It says
> > ```
> > Enter the URL from email: 
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > If you are on auto-pilot you might read it as
> > ```
> > Enter blah blah email:
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > You need to paste in the URL that starts
> > ```
> > https://download.llamameta.net/...)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Hope that helps people struggling
> 
> A number of us aren't on auto-pilot and are still having issues despite copying the correct link.

Actually, even after I re-cloned the repository and used the URL beginning with `https://download.llamameta.net/...)`, I still received a '403: Forbidden' message.

**Comment by uthpala1000** [comment]
you can download the block version here https://huggingface.co/TheBloke/Llama-2-70B-chat-GPTQ or any other  https://huggingface.co/TheBloke/

**Comment by se7enack** [comment]
Looks like the version of md5sum doesn't support the "-c" switch. If you edit this like and remove the switch md5 works correctly: 
From:
`(cd ${TARGET_FOLDER}"/${MODEL_PATH}" && md5sum -c checklist.chk)
`
To:
`(cd ${TARGET_FOLDER}"/${MODEL_PATH}" && md5sum checklist.chk)
`

**Comment by chengh99** [comment]
I had the same issue. Thanks for all the tips.  What I did now fixed my problems.  
1. removed the historical files tokenizer.model          tokenizer_checklist.chk
2. requested a new link, click & open it in a browser and paste the link to the command line when prompted
It is working for me now

**Comment by davidgao7** [comment]
I hardcoded the TARGET_FOLDER(where you want your model be downloaded) in the `download.sh` and rerun the script then it started downloading

**Comment by kevleyski** [comment]
Yeah Mac vs linux md5sum might be slightly different, remove the -c
(Metamates, can someone add a quick darwin os type check in the script)

**Comment by int29** [comment]
Thanks everyone, I was having the same issue, but I figured it out!

I thought when `download.sh` asked for an email, it meant to enter the email you used to register at "https://llama.meta.com/llama-downloads/", but actually, need to input the URL provided after agreeing to the terms.

**Comment by kevleyski** [comment]
Metamates, I feel this could be a common problem worth checking the logs and changing the wording in the prompt maybe

**Comment by faustoct1** [comment]
> Thanks everyone, I was having the same issue, but I figured it out!
> 
> I thought when `download.sh` asked for an email, it meant to enter the email you used to register at "https://llama.meta.com/llama-downloads/", but actually, need to input the URL provided after agreeing to the terms.

Thanks.
