### ISSUE TITLE
Approved, but unable to download weights

### ISSUE THREAD

**Issue by delip** [facebookresearch/llama#41]
When I run the `download.sh` I see this.
![image](https://user-images.githubusercontent.com/347398/222330335-e28a872c-6c00-4bc4-80e0-c0c60f431f77.png)

And I don't see any *.pth files in the download directory.

![image](https://user-images.githubusercontent.com/347398/222330437-2b69de38-9786-4f91-a1c4-e290178a40ba.png)

Any suggestions?

**Comment by dafraile** [comment]
I had the same issue downloading locally (Mac Os Monterey) but seems to be working fine in AWS (ubuntu)

**Comment by ramithuh** [comment]
I edited the code to handle that exception in dictionary defining on mac. 

```
# Copyright (c) Meta Platforms, Inc. and affiliates.
# This software may be used and distributed according to the terms of the GNU General Public License version 3.

PRESIGNED_URL=""             # replace with presigned url from email
MODEL_SIZE="7"  # edit this list with the model sizes you wish to download
TARGET_FOLDER="download"             # where all files should end up

declare -A N_SHARD_DICT

N_SHARD_DICT["7"]="0"
N_SHARD_DICT["13"]="1"
N_SHARD_DICT["30"]="3"
N_SHARD_DICT["65"]="7"

echo "Downloading tokenizer"
wget ${PRESIGNED_URL/'*'/"tokenizer.model"} -O ${TARGET_FOLDER}"/tokenizer.model"
wget ${PRESIGNED_URL/'*'/"tokenizer_checklist.chk"} -O ${TARGET_FOLDER}"/tokenizer_checklist.chk"

(cd ${TARGET_FOLDER} && md5 tokenizer_checklist.chk)

for i in ${MODEL_SIZE//,/ }
do
    echo "Downloading ${i}B"
    mkdir -p ${TARGET_FOLDER}"/${i}B"
    for s in $(seq -f "0%g" 0 ${N_SHARD_DICT[$i]})
    do
        echo "Downloading shard ${s}"
        wget ${PRESIGNED_URL/'*'/"${i}B/consolidated.${s}.pth"} -O ${TARGET_FOLDER}"/${i}B/consolidated.${s}.pth"
    done
    wget ${PRESIGNED_URL/'*'/"${i}B/params.json"} -O ${TARGET_FOLDER}"/${i}B/params.json"
    wget ${PRESIGNED_URL/'*'/"${i}B/checklist.chk"} -O ${TARGET_FOLDER}"/${i}B/checklist.chk"
    echo "Checking checksums"
    (cd ${TARGET_FOLDER}"/${i}B" && md5 checklist.chk)
done
```

**Comment by sumukshashidhar** [comment]
I end up getting either an Error 400: Bad Request, or a 403 when I replace the link. Just to confirm, it is a cloudfront link right?

![Screenshot 2023-03-01 at 10 49 47 PM](https://user-images.githubusercontent.com/46789005/222333980-2ab500b8-d78d-48b6-a04c-94a147b0d03b.png)

**Comment by Hannibal046** [comment]
Same problem on macOS. besides, I got the extra error:
```
download.sh: line 9: declare: -A: invalid option
```

**Comment by ramithuh** [comment]
Yup it's a cloudfront link. Curious why yours show a urldefence.com link.. maybe the network is blocking ?

**Comment by arqamrp** [comment]
@Hannibal046 I had got the same error message, solved it by installing wget and md5sum (coreutils).

**Comment by Hannibal046** [comment]
@arqamrp got it! Thanks

**Comment by tekspirit** [comment]
Are you using an m1 mac?  and if so, how did you get around the "nccl is missing" error?  Trying mps but need help.

**Comment by sapphire008** [comment]
For the error
```
download.sh: line 9: declare: -A: invalid option
```

I used
```bash
brew install bash
```
to install brew v5 and then use the bash installed by brew to download (in my case `/opt/homebrew/Cellar/bash/5.2.15/bin/bash download.sh`).

**Comment by yanzhangnlp** [comment]
<img width="503" alt="Screenshot 2023-03-02 at 1 19 36 PM" src="https://user-images.githubusercontent.com/7035357/222337949-a3bd5322-5090-4920-9559-79500098bd15.png">
Anyone else got this error?

**Comment by basujindal** [comment]
I am getting a 403 forbidden error:

```
HTTP request sent, awaiting response... 403 Forbidden
2023-03-02 05:39:58 ERROR 403: Forbidden.
```

Any suggestion would be appreciated? : /

**Comment by tekspirit** [comment]
> I am getting a 403 forbidden error:
> 
> ```
> HTTP request sent, awaiting response... 403 Forbidden
> 2023-03-02 05:39:58 ERROR 403: Forbidden.
> ```
> 
> Any suggestion would be appreciated? : /

you cannot use curl or wget directly.

**Comment by basujindal** [comment]
> > I am getting a 403 forbidden error:
> > ```
> > HTTP request sent, awaiting response... 403 Forbidden
> > 2023-03-02 05:39:58 ERROR 403: Forbidden.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Any suggestion would be appreciated? : /
> 
> you cannot use curl or wget directly.

Hi, thanks for the reply, I used the download.sh file with the received link (even removed the url defence) but I am still getting the error on Ubuntu 22

**Comment by tekspirit** [comment]
> > > I am getting a 403 forbidden error:
> > > ```
> > > HTTP request sent, awaiting response... 403 Forbidden
> > > 2023-03-02 05:39:58 ERROR 403: Forbidden.
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Any suggestion would be appreciated? : /
> > 
> > 
> > you cannot use curl or wget directly.
> 
> Hi, thanks for the reply, I used the download.sh file with the received link (even removed the url defence) but I am still getting the error on Ubuntu 22

did you use bash?  bash download.sh

**Comment by basujindal** [comment]
> > > > I am getting a 403 forbidden error:
> > > > ```
> > > > HTTP request sent, awaiting response... 403 Forbidden
> > > > 2023-03-02 05:39:58 ERROR 403: Forbidden.
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > Any suggestion would be appreciated? : /
> > > 
> > > 
> > > you cannot use curl or wget directly.
> > 
> > 
> > Hi, thanks for the reply, I used the download.sh file with the received link (even removed the url defence) but I am still getting the error on Ubuntu 22
> 
> did you use bash? bash download.sh

Yes, I did

**Comment by tekspirit** [comment]
I'm getting the checklist.chk and the params.json but the consolidated.xx.pth files are not coming down or do not exist.  Any ideas about this?

**Comment by G-U-N** [comment]
I tried to download it through mobaxterm on windows 10, and got the same error.  I fixed the error by installing coreutils.
```shell
apt install coreutils
```

**Comment by zhongtao93** [comment]
Using aria2 instead of wget

**Comment by harrywang** [comment]
> I edited the code to handle that exception in dictionary defining on mac.
> 
> ```
> # Copyright (c) Meta Platforms, Inc. and affiliates.
> # This software may be used and distributed according to the terms of the GNU General Public License version 3.
> 
> PRESIGNED_URL=""             # replace with presigned url from email
> MODEL_SIZE="7"  # edit this list with the model sizes you wish to download
> TARGET_FOLDER="download"             # where all files should end up
> 
> declare -A N_SHARD_DICT
> 
> N_SHARD_DICT["7"]="0"
> N_SHARD_DICT["13"]="1"
> N_SHARD_DICT["30"]="3"
> N_SHARD_DICT["65"]="7"
> 
> echo "Downloading tokenizer"
> wget ${PRESIGNED_URL/'*'/"tokenizer.model"} -O ${TARGET_FOLDER}"/tokenizer.model"
> wget ${PRESIGNED_URL/'*'/"tokenizer_checklist.chk"} -O ${TARGET_FOLDER}"/tokenizer_checklist.chk"
> 
> (cd ${TARGET_FOLDER} && md5 tokenizer_checklist.chk)
> 
> for i in ${MODEL_SIZE//,/ }
> do
>     echo "Downloading ${i}B"
>     mkdir -p ${TARGET_FOLDER}"/${i}B"
>     for s in $(seq -f "0%g" 0 ${N_SHARD_DICT[$i]})
>     do
>         echo "Downloading shard ${s}"
>         wget ${PRESIGNED_URL/'*'/"${i}B/consolidated.${s}.pth"} -O ${TARGET_FOLDER}"/${i}B/consolidated.${s}.pth"
>     done
>     wget ${PRESIGNED_URL/'*'/"${i}B/params.json"} -O ${TARGET_FOLDER}"/${i}B/params.json"
>     wget ${PRESIGNED_URL/'*'/"${i}B/checklist.chk"} -O ${TARGET_FOLDER}"/${i}B/checklist.chk"
>     echo "Checking checksums"
>     (cd ${TARGET_FOLDER}"/${i}B" && md5 checklist.chk)
> done
> ```

I had the same problem and this works! Thanks @ramithuh

**Comment by drewgillson** [comment]
Here is a version of download.sh that works with /bin/zsh (zsh 5.8.1 (x86_64-apple-darwin22.0)
```
# Copyright (c) Meta Platforms, Inc. and affiliates.
# This software may be used and distributed according to the terms of the GNU General Public License version 3.

PRESIGNED_URL=""             # replace with presigned url from email
MODEL_SIZE="X7B,X13B,X30B,X65B"  # edit this list with the model sizes you wish to download
TARGET_FOLDER="."             # where all files should end up

declare -a N_SHARD_DICT

N_SHARD_DICT["X7B"]="0"
N_SHARD_DICT["X13B"]="1"
N_SHARD_DICT["X30B"]="3"
N_SHARD_DICT["X65B"]="7"

echo "Downloading tokenizer"
wget ${PRESIGNED_URL/'*'/"tokenizer.model"} -O ${TARGET_FOLDER}"/tokenizer.model"
wget ${PRESIGNED_URL/'*'/"tokenizer_checklist.chk"} -O ${TARGET_FOLDER}"/tokenizer_checklist.chk"

(cd ${TARGET_FOLDER} && md5 -r tokenizer_checklist.chk)

for i in ${MODEL_SIZE//,/ }
do
    m="${i:1}" # remove preceding X
    echo "Downloading ${m}"
    mkdir -p ${TARGET_FOLDER}"/${m}"
    for s in $(seq -f "0%g" 0 ${N_SHARD_DICT[$i]})
    do
        echo ${PRESIGNED_URL/'*'/"${m}/consolidated.${s}.pth"} -O ${TARGET_FOLDER}"/${m}/consolidated.${s}.pth"
        wget ${PRESIGNED_URL/'*'/"${m}/consolidated.${s}.pth"} -O ${TARGET_FOLDER}"/${m}/consolidated.${s}.pth"
    done
    wget ${PRESIGNED_URL/'*'/"${m}/params.json"} -O ${TARGET_FOLDER}"/${m}/params.json"
    wget ${PRESIGNED_URL/'*'/"${m}/checklist.chk"} -O ${TARGET_FOLDER}"/${m}/checklist.chk"
    echo "Checking checksums"
    (cd ${TARGET_FOLDER}"/${m}" && md5 -r checklist.chk)
done
```

**Comment by kli017** [comment]
**Connecting to dobf1k6cxlizq.cloudfront.net|13.33.45.217|:443... connected.
ERROR: cannot verify dobf1k6cxlizq.cloudfront.net's certificate, issued by `/C=US/O=Amazon/CN=Amazon RSA 2048 M01':**
Hello anyone meet this error?

**Comment by riskyhomo** [comment]
i got approved but unable to download the 7B weight , now please tell what steps should be followed in order to access the 7B weight i have installed all the tools required for it , thanking you

**Comment by tekspirit** [comment]
> i got approved but unable to download the 7B weight , now please tell what steps should be followed in order to access the 7B weight i have installed all the tools required for it , thanking you

If you on mac, there is a script here in the issues you can use that works.

**Comment by johnwalterdennis** [comment]
![Screenshot (23)](https://user-images.githubusercontent.com/102927782/222989165-e32a5c04-efdf-4f86-b85d-2f450a0f924f.png)
this is the error i get when i try to run the script, any fix?

**Comment by trekrollercoaster** [comment]
> I end up getting either an Error 400: Bad Request, or a 403 when I replace the link. Just to confirm, it is a cloudfront link right?
> 
> ![Screenshot 2023-03-01 at 10 49 47 PM](https://user-images.githubusercontent.com/46789005/222333980-2ab500b8-d78d-48b6-a04c-94a147b0d03b.png)

https://github.com/facebookresearch/llama/issues/57#issuecomment-1455086931

This seems to be a problem of the network region. I set the agent to Japan or the United States to solve this problem

**Comment by Vitaly-Protasov** [comment]
Still getting **ERROR 403: Forbidden.**. How to fix it?

**Comment by cgongye** [comment]
I still have issues, can you post your checksum files here?

e.g. in the download folder, the output of 

`find . -name "*.chk" -exec cat {} +`

**Comment by mpskex** [comment]
Just wrote a python script to replicate who would be done in bash
```python
from os import path, makedirs, getcwd, chdir
from argparse import ArgumentParser
import logging
import subprocess

logging.basicConfig(level=logging.DEBUG)

p = ArgumentParser("Download LLaMA")
p.add_argument('--check-only', '-c', action='store_true', help="Only doing File")
p.add_argument('--dryrun', '-d', action='store_true', help="Dryrun, only print but no execute")
p.add_argument('--target', '-o', default='downloads', type=str, help="Target output diretory")
p.add_argument('--models', '-m', default=["7B","13B","30B","65B"], nargs='+', help="Models you want to download")
args = p.parse_args()

N_SHARD_DICT = {}
N_SHARD_DICT["7B"] = 0
N_SHARD_DICT["13B"] = 1
N_SHARD_DICT["30B"] = 3
N_SHARD_DICT["65B"] = 7

assert [m in ["7B","13B","30B","65B"] for m in args.models]
TARGET_FOLDER=lambda x: path.join(args.target, x)
PRESIGNED_URL=lambda x: f"https://dobf1k6cxlizq.cloudfront.net/{x}?Policy=<ur-rest-of-presign-url>"

makedirs(TARGET_FOLDER(""), exist_ok=True)

models = ['tokenizer.model', "tokenizer_checklist.chk"]
for s in args.models:
    makedirs(TARGET_FOLDER(s), exist_ok=True)
    models.extend([f"{s}/consolidated.0{n}.pth" for n in range(N_SHARD_DICT[s]+1)])
    models.extend([f"{s}/{f}" for f in ["params.json", "checklist.chk"]])

for i, n in enumerate(models):
    logging.info(f"[{i}/{len(models)}]Downloding {n}...")
    wget_str = f"wget -c {PRESIGNED_URL(n)} -O {TARGET_FOLDER(n)}"
    if args.dryrun:
        logging.debug(f"-- {wget_str}")
    else:
        if not args.check_only:
            subprocess.run(wget_str.split(' '))


for i, s in enumerate(args.models):
    cmd = "md5sum -c checklist.chk"
    logging.info(f"[{i}/{len(args.models)}] Checking Model {s}...")
    if args.dryrun:
        logging.debug(f"-- {cmd}")
    else:
        subprocess.run(cmd.split(' '), cwd=TARGET_FOLDER(s))
```

**Comment by vincentwi** [comment]
> Just wrote a python script to replicate what would be done in bash
> 
> ```python
> from os import path, makedirs, getcwd, chdir
> from argparse import ArgumentParser
> import logging
> import subprocess
> 
> logging.basicConfig(level=logging.DEBUG)
> 
> p = ArgumentParser("Download LLaMA")
> p.add_argument('--check-only', '-c', action='store_true', help="Only doing File")
> p.add_argument('--dryrun', '-d', action='store_true', help="Dryrun, only print but no execute")
> p.add_argument('--target', '-o', default='downloads', type=str, help="Target output diretory")
> p.add_argument('--models', '-m', default=["7B","13B","30B","65B"], nargs='+', help="Models you want to download")
> args = p.parse_args()
> 
> N_SHARD_DICT = {}
> N_SHARD_DICT["7B"] = 0
> N_SHARD_DICT["13B"] = 1
> N_SHARD_DICT["30B"] = 3
> N_SHARD_DICT["65B"] = 7
> 
> assert [m in ["7B","13B","30B","65B"] for m in args.models]
> TARGET_FOLDER=lambda x: path.join(args.target, x)
> PRESIGNED_URL=lambda x: f"https://dobf1k6cxlizq.cloudfront.net/{x}?Policy=<ur-rest-of-presign-url>"
> 
> makedirs(TARGET_FOLDER(""), exist_ok=True)
> 
> models = ['tokenizer.model', "tokenizer_checklist.chk"]
> for s in args.models:
>     makedirs(TARGET_FOLDER(s), exist_ok=True)
>     models.extend([f"{s}/consolidated.0{n}.pth" for n in range(N_SHARD_DICT[s]+1)])
>     models.extend([f"{s}/{f}" for f in ["params.json", "checklist.chk"]])
> 
> for i, n in enumerate(models):
>     logging.info(f"[{i}/{len(models)}]Downloding {n}...")
>     wget_str = f"wget -c {PRESIGNED_URL(n)} -O {TARGET_FOLDER(n)}"
>     if args.dryrun:
>         logging.debug(f"-- {wget_str}")
>     else:
>         if not args.check_only:
>             subprocess.run(wget_str.split(' '))
> 
> 
> for i, s in enumerate(args.models):
>     cmd = "md5sum -c checklist.chk"
>     logging.info(f"[{i}/{len(args.models)}] Checking Model {s}...")
>     if args.dryrun:
>         logging.debug(f"-- {cmd}")
>     else:
>         subprocess.run(cmd.split(' '), cwd=TARGET_FOLDER(s))
> ```

I was also getting the `ERROR 403: Forbidden` error when connecting to after using @ramithu 's [above code](https://github.com/facebookresearch/llama/issues/41#issuecomment-1451290160). Reinstalling brew, alternative curl, wget and aria2 didn't work either. Tried company wifi, home wifi and personal hotspot, no success, still same error. 
However the [above quoted code](https://github.com/facebookresearch/llama/issues/41#issuecomment-1459518524) from @mpskex was successful. Just create a new download.py file, copy pasta, change lines 11 and 23 to your respective default `TARGET_FOLDER` and Presigned_URL and it should work when you `python download.py` in terminal. 
Thank you @mpskex

**Comment by mpskex** [comment]
> > Just wrote a python script to replicate what would be done in bash
> > ```python
> > from os import path, makedirs, getcwd, chdir
> > from argparse import ArgumentParser
> > import logging
> > import subprocess
> > 
> > logging.basicConfig(level=logging.DEBUG)
> > 
> > p = ArgumentParser("Download LLaMA")
> > p.add_argument('--check-only', '-c', action='store_true', help="Only doing File")
> > p.add_argument('--dryrun', '-d', action='store_true', help="Dryrun, only print but no execute")
> > p.add_argument('--target', '-o', default='downloads', type=str, help="Target output diretory")
> > p.add_argument('--models', '-m', default=["7B","13B","30B","65B"], nargs='+', help="Models you want to download")
> > args = p.parse_args()
> > 
> > N_SHARD_DICT = {}
> > N_SHARD_DICT["7B"] = 0
> > N_SHARD_DICT["13B"] = 1
> > N_SHARD_DICT["30B"] = 3
> > N_SHARD_DICT["65B"] = 7
> > 
> > assert [m in ["7B","13B","30B","65B"] for m in args.models]
> > TARGET_FOLDER=lambda x: path.join(args.target, x)
> > PRESIGNED_URL=lambda x: f"https://dobf1k6cxlizq.cloudfront.net/{x}?Policy=<ur-rest-of-presign-url>"
> > 
> > makedirs(TARGET_FOLDER(""), exist_ok=True)
> > 
> > models = ['tokenizer.model', "tokenizer_checklist.chk"]
> > for s in args.models:
> >     makedirs(TARGET_FOLDER(s), exist_ok=True)
> >     models.extend([f"{s}/consolidated.0{n}.pth" for n in range(N_SHARD_DICT[s]+1)])
> >     models.extend([f"{s}/{f}" for f in ["params.json", "checklist.chk"]])
> > 
> > for i, n in enumerate(models):
> >     logging.info(f"[{i}/{len(models)}]Downloding {n}...")
> >     wget_str = f"wget -c {PRESIGNED_URL(n)} -O {TARGET_FOLDER(n)}"
> >     if args.dryrun:
> >         logging.debug(f"-- {wget_str}")
> >     else:
> >         if not args.check_only:
> >             subprocess.run(wget_str.split(' '))
> > 
> > 
> > for i, s in enumerate(args.models):
> >     cmd = "md5sum -c checklist.chk"
> >     logging.info(f"[{i}/{len(args.models)}] Checking Model {s}...")
> >     if args.dryrun:
> >         logging.debug(f"-- {cmd}")
> >     else:
> >         subprocess.run(cmd.split(' '), cwd=TARGET_FOLDER(s))
> > ```
> 
> I was also getting the `ERROR 403: Forbidden` error when connecting to after using @ramithu 's [above code](https://github.com/facebookresearch/llama/issues/41#issuecomment-1451290160). Reinstalling brew, alternative curl, wget and aria2 didn't work either. Tried company wifi, home wifi and personal hotspot, no success, still same error. However the [above quoted code](https://github.com/facebookresearch/llama/issues/41#issuecomment-1459518524) from @mpskex was successful. Just create a new download.py file, copy pasta, change lines 11 and 23 to your respective default `TARGET_FOLDER` and `PRESIGNED_URL` and it should work when you `python download.py` in terminal. Thank you @mpskex
> 
> However for the 7B and 13B models, the `consolidated.00.pth` file don't download with error:
> 
> > `Resolving dobf1k6cxlizq.cloudfront.net (dobf1k6cxlizq.cloudfront.net)... failed: nodename nor servname provided, or not known.`
> > `wget: unable to resolve host address ‘dobf1k6cxlizq.cloudfront.net’`

I would suggest you replace the prefix of that url `dobf1k6cxlizq.cloudfront.net` into `<prefix-in-your-url>.cloudfront.net`. That may fix your problem.

**Comment by sidsvash26** [comment]
> Just wrote a python script to replicate what would be done in bash
> 
> ```python
> from os import path, makedirs, getcwd, chdir
> from argparse import ArgumentParser
> import logging
> import subprocess
> 
> logging.basicConfig(level=logging.DEBUG)
> 
> p = ArgumentParser("Download LLaMA")
> p.add_argument('--check-only', '-c', action='store_true', help="Only doing File")
> p.add_argument('--dryrun', '-d', action='store_true', help="Dryrun, only print but no execute")
> p.add_argument('--target', '-o', default='downloads', type=str, help="Target output diretory")
> p.add_argument('--models', '-m', default=["7B","13B","30B","65B"], nargs='+', help="Models you want to download")
> args = p.parse_args()
> 
> N_SHARD_DICT = {}
> N_SHARD_DICT["7B"] = 0
> N_SHARD_DICT["13B"] = 1
> N_SHARD_DICT["30B"] = 3
> N_SHARD_DICT["65B"] = 7
> 
> assert [m in ["7B","13B","30B","65B"] for m in args.models]
> TARGET_FOLDER=lambda x: path.join(args.target, x)
> PRESIGNED_URL=lambda x: f"https://<ur-prefix-of-presigned-url>.cloudfront.net/{x}?Policy=<ur-rest-of-presign-url>"
> 
> makedirs(TARGET_FOLDER(""), exist_ok=True)
> 
> models = ['tokenizer.model', "tokenizer_checklist.chk"]
> for s in args.models:
>     makedirs(TARGET_FOLDER(s), exist_ok=True)
>     models.extend([f"{s}/consolidated.0{n}.pth" for n in range(N_SHARD_DICT[s]+1)])
>     models.extend([f"{s}/{f}" for f in ["params.json", "checklist.chk"]])
> 
> for i, n in enumerate(models):
>     logging.info(f"[{i}/{len(models)}]Downloding {n}...")
>     wget_str = f"wget -c {PRESIGNED_URL(n)} -O {TARGET_FOLDER(n)}"
>     if args.dryrun:
>         logging.debug(f"-- {wget_str}")
>     else:
>         if not args.check_only:
>             subprocess.run(wget_str.split(' '))
> 
> 
> for i, s in enumerate(args.models):
>     cmd = "md5sum -c checklist.chk"
>     logging.info(f"[{i}/{len(args.models)}] Checking Model {s}...")
>     if args.dryrun:
>         logging.debug(f"-- {cmd}")
>     else:
>         subprocess.run(cmd.split(' '), cwd=TARGET_FOLDER(s))
> ```

I was also getting the 403 Forbidden error when running the bash script. This python script worked perfectly for me on Mac OS Ventura 13.0.1 M1 Pro processor. Thanks!

**Comment by cozmoguy** [comment]
When I ran this command in colab

`!torchrun --nproc_per_node 1 example.py --ckpt_dir '/model_7b/7B' --tokenizer_path '/model_7b/tokenizer.model'`

I received this error 

`> initializing model parallel with size 1
> initializing ddp with size 1
> initializing pipeline with size 1
Traceback (most recent call last):
  File "/content/drive/MyDrive/Colab Notebooks/llama-main/llama-main/example.py", line 119, in <module>
    fire.Fire(main)
  File "/usr/local/lib/python3.9/dist-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/usr/local/lib/python3.9/dist-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/usr/local/lib/python3.9/dist-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/content/drive/MyDrive/Colab Notebooks/llama-main/llama-main/example.py", line 78, in main
    generator = load(
  File "/content/drive/MyDrive/Colab Notebooks/llama-main/llama-main/example.py", line 42, in load
    assert world_size == len(
AssertionError: Loading a checkpoint for MP=0 but world size is 1
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 10284) of binary: /usr/bin/python3
Traceback (most recent call last):
  File "/usr/local/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/dist-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/usr/local/lib/python3.9/dist-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/usr/local/lib/python3.9/dist-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/usr/local/lib/python3.9/dist-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
example.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-04-05_09:44:50
  host      : 5b0863632bc5
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 10284)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html`

**Comment by borisalmonacid** [comment]
> 
same error, have you been able to solve it?
win10 environment

**Comment by borisalmonacid** [comment]
> **Connecting to dobf1k6cxlizq.cloudfront.net|13.33.45.217|:443... connected. ERROR: cannot verify dobf1k6cxlizq.cloudfront.net's certificate, issued by `/C=US/O=Amazon/CN=Amazon RSA 2048 M01':** Hello anyone meet this error?

same error, have you been able to solve it?
win10 environment

**Comment by sergiotasconmorales** [comment]
I am also getting the ERROR 403: Forbidden error on Ubuntu. I tried all the proposed solutions in this issue but nothing worked :'(

**Comment by sergsb** [comment]
The same (

**Comment by sacrrie** [comment]
Same here in JP. I am starting to wonder if their server has any issues.

**Comment by BarkaviSJ** [comment]
> I am also getting the ERROR 403: Forbidden error on Ubuntu. I tried all the proposed solutions in this issue but nothing worked :'(

Same 403 forbidden error for me both in MAC and Linux!

**Comment by Luxios22** [comment]
same 403 forbidden error both in Mac and Linux in Singapore

**Comment by borisalmonacid** [comment]
> same 403 forbidden error both in Mac and Linux in Singapore

@Luxios22 @BarkaviSJ maybe with VPN?

**Comment by Luxios22** [comment]
> > same 403 forbidden error both in Mac and Linux in Singapore
> 
> @Luxios22 @BarkaviSJ maybe with VPN?

You mean VPN of which place?

**Comment by borisalmonacid** [comment]
> > > same 403 forbidden error both in Mac and Linux in Singapore
> > 
> > 
> > @Luxios22 @BarkaviSJ maybe with VPN?
> 
> You mean VPN of which place?

@Luxios22 yes, I simple test for discard, but, I had different problems, and finally the version of python with curl worked for me in a 5G connection

**Comment by Luxios22** [comment]
> 

Curl version python code did help on Mac, but this time I got Access Denied shown in params.json, which is really weird. I am using the link LLaMA sent to me.
Anyway thanks, I may try to contact the LLaMA team.

**Comment by Luxios22** [comment]
> > > > same 403 forbidden error both in Mac and Linux in Singapore
> > > 
> > > 
> > > @Luxios22 @BarkaviSJ maybe with VPN?
> > 
> > 
> > You mean VPN of which place?
> 
> @Luxios22 yes, I simple test for discard, but, I had different problems, and finally the version of python with curl worked for me in a 5G connection

Curl version python code did help on Mac, but this time I got Access Denied shown in params.json, which is really weird. I am using the link LLaMA sent to me.
Anyway thanks, I may try to contact the LLaMA team.

**Comment by BarkaviSJ** [comment]
> > same 403 forbidden error both in Mac and Linux in Singapore
> 
> @Luxios22 @BarkaviSJ @sacrrie maybe with VPN?
> 
> anyway, I used this code in the python version (curl download)
> 
> ```
> > for i, n in enumerate(models):
> >     logging.info(f"[{i}/{len(models)}]Downloding {n}...")
> >     curl_str = f"curl {PRESIGNED_URL(n)} -o {TARGET_FOLDER(n)}"
> >     print("---- RULE: ", curl_str)
> >     if args.dryrun:
> >         logging.debug(f"-- {curl_str}")
> >     else:
> >         if not args.check_only:
> >             subprocess.run(curl_str.split(' '))
> ```

@borisalmonacid Thank you for this suggestion. 403 Forbidden is solved. Looks like the download is taking longer, even for the 7B model. Any rough estimate as to how long the download takes?

                                 Dload  Upload   Total   Spent    Left  Speed
100   110  100   110    0     0   1095      0 --:--:-- --:--:-- --:--:--  1100
**INFO:root:[0/1] Checking Model 7B...**

**Comment by sergiotasconmorales** [comment]
> > anyway, I used this code in the python version (curl download)
> > ```
> > > for i, n in enumerate(models):
> > >     logging.info(f"[{i}/{len(models)}]Downloding {n}...")
> > >     curl_str = f"curl {PRESIGNED_URL(n)} -o {TARGET_FOLDER(n)}"
> > >     print("---- RULE: ", curl_str)
> > >     if args.dryrun:
> > >         logging.debug(f"-- {curl_str}")
> > >     else:
> > >         if not args.check_only:
> > >             subprocess.run(curl_str.split(' '))
> > ```
> 
> @borisalmonacid Thank you for this suggestion. 403 Forbidden is solved. Looks like the download is taking longer, even for the 7B model. Any rough estimate as to how long the download takes?
> 
> ```
>                              Dload  Upload   Total   Spent    Left  Speed
> ```
> 
> 100 110 100 110 0 0 1095 0 --:--:-- --:--:-- --:--:-- 1100 **INFO:root:[0/1] Checking Model 7B...**

@BarkaviSJ did that work for you on Mac or Linux? I tried it on Linux but it didn't solve the problem.

**Comment by BarkaviSJ** [comment]
> > > anyway, I used this code in the python version (curl download)
> > > ```
> > > > for i, n in enumerate(models):
> > > >     logging.info(f"[{i}/{len(models)}]Downloding {n}...")
> > > >     curl_str = f"curl {PRESIGNED_URL(n)} -o {TARGET_FOLDER(n)}"
> > > >     print("---- RULE: ", curl_str)
> > > >     if args.dryrun:
> > > >         logging.debug(f"-- {curl_str}")
> > > >     else:
> > > >         if not args.check_only:
> > > >             subprocess.run(curl_str.split(' '))
> > > ```
> > 
> > 
> > @borisalmonacid Thank you for this suggestion. 403 Forbidden is solved. Looks like the download is taking longer, even for the 7B model. Any rough estimate as to how long the download takes?
> > ```
> >                              Dload  Upload   Total   Spent    Left  Speed
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 100 110 100 110 0 0 1095 0 --:--:-- --:--:-- --:--:-- 1100 **INFO:root:[0/1] Checking Model 7B...**
> 
> @BarkaviSJ did that work for you on Mac or Linux? I tried it on Linux but it didn't solve the problem.

That worked for me (curl for 403 forbidden alone) in MAC. But, I still have the same issue as mentioned by @Luxios22. **Access Denied shown in params.json**

I installed **brew install md5sha1sum** yet it is NOT working :(

**Comment by aaanh** [comment]
I'm also having the same 403 forbidden error.
My machine is running:
- OS: Red Hat Enterprise Linux 9.1 (Plow) x86_64
- Kernel: 5.14.0-162.22.2.el9_1.x86_64
- Packages:
     - curl.x86_64: 7.76.1-19.el9_1.2
     - wget.x86_64: 1.21.1-7.el9
     - Python 3.9.14

I've tried: 
- updating everything using `dnf`, reinstalling wget, curl, and coreutils
- VPN tunneled to a data center in the US (I'm based in Canada)
- Both the originally provided `download.sh`, the `download.py` ones above
- All of the above but on Ubuntu Desktop 22.10 (native, not VM)

No luck so far 😅

**Comment by borisalmonacid** [comment]
> > > same 403 forbidden error both in Mac and Linux in Singapore
> > 
> > 
> > @Luxios22 @BarkaviSJ @sacrrie maybe with VPN?
> > anyway, I used this code in the python version (curl download)
> > ```
> > > for i, n in enumerate(models):
> > >     logging.info(f"[{i}/{len(models)}]Downloding {n}...")
> > >     curl_str = f"curl {PRESIGNED_URL(n)} -o {TARGET_FOLDER(n)}"
> > >     print("---- RULE: ", curl_str)
> > >     if args.dryrun:
> > >         logging.debug(f"-- {curl_str}")
> > >     else:
> > >         if not args.check_only:
> > >             subprocess.run(curl_str.split(' '))
> > ```
> 
> @borisalmonacid Thank you for this suggestion. 403 Forbidden is solved. Looks like the download is taking longer, even for the 7B model. Any rough estimate as to how long the download takes?
> 
> ```
>                              Dload  Upload   Total   Spent    Left  Speed
> ```
> 
> 100 110 100 110 0 0 1095 0 --:--:-- --:--:-- --:--:-- 1100 **INFO:root:[0/1] Checking Model 7B...**

@BarkaviSJ 10-15 minutes in 5G phone,.

**Comment by borisalmonacid** [comment]
> > > > anyway, I used this code in the python version (curl download)
> > > > ```
> > > > > for i, n in enumerate(models):
> > > > >     logging.info(f"[{i}/{len(models)}]Downloding {n}...")
> > > > >     curl_str = f"curl {PRESIGNED_URL(n)} -o {TARGET_FOLDER(n)}"
> > > > >     print("---- RULE: ", curl_str)
> > > > >     if args.dryrun:
> > > > >         logging.debug(f"-- {curl_str}")
> > > > >     else:
> > > > >         if not args.check_only:
> > > > >             subprocess.run(curl_str.split(' '))
> > > > ```
> > > 
> > > 
> > > @borisalmonacid Thank you for this suggestion. 403 Forbidden is solved. Looks like the download is taking longer, even for the 7B model. Any rough estimate as to how long the download takes?
> > > ```
> > >                              Dload  Upload   Total   Spent    Left  Speed
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 100 110 100 110 0 0 1095 0 --:--:-- --:--:-- --:--:-- 1100 **INFO:root:[0/1] Checking Model 7B...**
> > 
> > 
> > @BarkaviSJ did that work for you on Mac or Linux? I tried it on Linux but it didn't solve the problem.
> 
> That worked for me (curl for 403 forbidden alone) in MAC. But, I still have the same issue as mentioned by @Luxios22. **Access Denied shown in params.json**
> 
> I installed **brew install md5sha1sum** yet it is NOT working.

@BarkaviSJ you must use an independent md5 software for the check, specifically for your operating system/distribution.
In fact, I did the md5-sum in Windows 10 in a manual way.

![image](https://user-images.githubusercontent.com/28852633/233242721-0b6397d2-2586-4013-9b36-2f728015f039.png)

**Comment by mgagvani** [comment]
I'm getting the same error, using both `download.sh` and the Python script commented above by @mpskex. I'm using WSL2 with Python 3.10.6 and wget 1.21.2.

**Comment by amnank** [comment]
How do I run the download.sh bash script on windows on cmd?

**Comment by amnank** [comment]
![image](https://user-images.githubusercontent.com/74487111/233931132-bbe7e273-5314-47ed-b28f-6d7c7ef253b4.png)

Anyone else getting this issue?

**Comment by VladimirVincan** [comment]
> 

Doesn't work, I also tried to change the -O flag with aria2's -o flag.

**Comment by montyhall** [comment]
i just got a new presigned URL and ran FAIR's own download.sh and it is working.

**Comment by yskolnick** [comment]
> > > > > same 403 forbidden error both in Mac and Linux in Singapore
> > > > 
> > > > 
> > > > @Luxios22 @BarkaviSJ maybe with VPN?
> > > 
> > > 
> > > You mean VPN of which place?
> > 
> > 
> > @Luxios22 yes, I simple test for discard, but, I had different problems, and finally the version of python with curl worked for me in a 5G connection
> 
> How did u solve the signature, key-value pair and md5 problem in windows?



> ![image](https://user-images.githubusercontent.com/74487111/233931132-bbe7e273-5314-47ed-b28f-6d7c7ef253b4.png)
> 
> Anyone else getting this issue?

choco install wget 
got rid of the wget issue if you have: (https://chocolatey.org/install)
I can't solve the md5 yet

**Comment by abalhomaid** [comment]
I added `#!/bin/bash` at the first line and `chmod +x download.sh` for it to work

**Comment by vkp2020** [comment]
Finally I managed to fix all issues and download the model weights thanks to the comments from this group. I am writing this to help others investigate and fix it systematically:

Step-1: Read the output. If you see this error
 --- download.sh: line 9: declare: -A: invalid option ---
Then do
brew install bash
to install brew v5 and then use the bash installed by brew to download  latest version of bash (the problem is that the version of bash that ships with Mac doesn't have option -A)
and then run this (make sure to replace the version digits if your version is different than this)

/opt/homebrew/Cellar/bash/5.2.15/bin/bash download.sh 

Step-2: If you see wget not found or checksum not found errors it means that these tools are not installed, install them:

brew install wget
brew install md5sha1sum

and run the download.sh as described above

Step-3: If you get 403 Forbidden error it means that you are messing up with settings. Make sure that you have copy pasted the 'exact' url as you received (it has a * sign in it which is replaced by elected model) do not change anything in the url. and for model selection just keep your selected option from the list. e.g.

MODEL_SIZE="7B"  # edit this list with the model sizes you wish to download
or 
MODEL_SIZE="13B"  # edit this list with the model sizes you wish to download
like this. 
DO NOT Change anything else, just write the name of the folder where you want to store model weights. bash will create the folder if it does not exist.

ENJOY...

**Comment by soumakmo** [comment]
The script only downloads consolidated.00.pth and consolidated.01.pth files for every model. Anyone else facing this problem?

**Comment by vamgan** [comment]
I was getting a 403 error with the bash script but I was able to successfully start downloading through the python script. The download speeds are very slow for me is it normal? It's showing more than 5hrs for 1 model.

**Comment by VidarSolutions** [comment]
> #!/bin/bash

[drewgillson](https://github.com/drewgillson)'s new script posted mar 2 2023 worked for me. 
Thanks Drew!!!
I had to make sure the wget commands were all on one line somehow copy and pasting from the browser to the terminal windows added a carriage return and thus had an issue with the output files not existing instead of creating them.  once I made all the wget commands were a single line the script ran perfectly and downloaded them files.

was 
`wget ${PRESIGNED_URL/'*'/"tokenizer.model"} -O `

`${TARGET_FOLDER}"/tokenizer.model"`
`wget ${PRESIGNED_URL/'*'/"tokenizer_checklist.chk"} -O `

`${TARGET_FOLDER}"/tokenizer_checklist.chk"`

should have been:

`wget ${PRESIGNED_URL/'*'/"tokenizer.model"} -O ${TARGET_FOLDER}"/tokenizer.model"`

`wget ${PRESIGNED_URL/'*'/"tokenizer_checklist.chk"} -O ${TARGET_FOLDER}"/tokenizer_checklist.chk" `

**Comment by resperic** [comment]
Ubuntu 22.04

I inserted the link into the .sh file, and tried to run it:

bash download.sh

This resulted in the following:

(base) rafa@monster:~/llama$ bash download.sh
Downloading tokenizer
/tokenizer.model: Permission denied
/tokenizer_checklist.chk: Permission denied
md5sum: tokenizer_checklist.chk: No such file or directory
Downloading 7B
mkdir: cannot create directory ‘/7B’: Permission denied
/7B/consolidated.00.pth: No such file or directory
/7B/params.json: No such file or directory
/7B/checklist.chk: No such file or directory
Checking checksums
download.sh: line 34: cd: /7B: No such file or directory
Downloading 13B
mkdir: cannot create directory ‘/13B’: Permission denied
/13B/consolidated.00.pth: No such file or directory
/13B/consolidated.01.pth: No such file or directory
/13B/params.json: No such file or directory
/13B/checklist.chk: No such file or directory
Checking checksums
download.sh: line 34: cd: /13B: No such file or directory
Downloading 30B
mkdir: cannot create directory ‘/30B’: Permission denied
/30B/consolidated.00.pth: No such file or directory
/30B/consolidated.01.pth: No such file or directory
/30B/consolidated.02.pth: No such file or directory
/30B/consolidated.03.pth: No such file or directory
/30B/params.json: No such file or directory
/30B/checklist.chk: No such file or directory
Checking checksums
download.sh: line 34: cd: /30B: No such file or directory
Downloading 65B
mkdir: cannot create directory ‘/65B’: Permission denied
/65B/consolidated.00.pth: No such file or directory
/65B/consolidated.01.pth: No such file or directory
/65B/consolidated.02.pth: No such file or directory
/65B/consolidated.03.pth: No such file or directory
/65B/consolidated.04.pth: No such file or directory
/65B/consolidated.05.pth: No such file or directory
/65B/consolidated.06.pth: No such file or directory
/65B/consolidated.07.pth: No such file or directory
/65B/params.json: No such file or directory
/65B/checklist.chk: No such file or directory
Checking checksums
download.sh: line 34: cd: /65B: No such file or directory

**Comment by iamlajoya21** [comment]
> I edited the code to handle that exception in dictionary defining on mac.
> 
> ```
> # Copyright (c) Meta Platforms, Inc. and affiliates.
> # This software may be used and distributed according to the terms of the GNU General Public License version 3.
> 
> PRESIGNED_URL=""             # replace with presigned url from email
> MODEL_SIZE="7"  # edit this list with the model sizes you wish to download
> TARGET_FOLDER="download"             # where all files should end up
> 
> declare -A N_SHARD_DICT
> 
> N_SHARD_DICT["7"]="0"
> N_SHARD_DICT["13"]="1"
> N_SHARD_DICT["30"]="3"
> N_SHARD_DICT["65"]="7"
> 
> echo "Downloading tokenizer"
> wget ${PRESIGNED_URL/'*'/"tokenizer.model"} -O ${TARGET_FOLDER}"/tokenizer.model"
> wget ${PRESIGNED_URL/'*'/"tokenizer_checklist.chk"} -O ${TARGET_FOLDER}"/tokenizer_checklist.chk"
> 
> (cd ${TARGET_FOLDER} && md5 tokenizer_checklist.chk)
> 
> for i in ${MODEL_SIZE//,/ }
> do
>     echo "Downloading ${i}B"
>     mkdir -p ${TARGET_FOLDER}"/${i}B"
>     for s in $(seq -f "0%g" 0 ${N_SHARD_DICT[$i]})
>     do
>         echo "Downloading shard ${s}"
>         wget ${PRESIGNED_URL/'*'/"${i}B/consolidated.${s}.pth"} -O ${TARGET_FOLDER}"/${i}B/consolidated.${s}.pth"
>     done
>     wget ${PRESIGNED_URL/'*'/"${i}B/params.json"} -O ${TARGET_FOLDER}"/${i}B/params.json"
>     wget ${PRESIGNED_URL/'*'/"${i}B/checklist.chk"} -O ${TARGET_FOLDER}"/${i}B/checklist.chk"
>     echo "Checking checksums"
>     (cd ${TARGET_FOLDER}"/${i}B" && md5 checklist.chk)
> done
> ```

this works - thanks a bunch

**Comment by jspisak** [comment]
Closing this issue but cc'ing @samuelselvan for FYI and future script updates..

**Comment by Iazzetta** [comment]
Don't need update  download.sh, just install:

```
brew install wget rhash coreutils
```
